
services:
  node:
    image: node:18.15.0-alpine3.17
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
    networks:
      - fct
    command: "npm start"
networks:
  fct:
    external: true
  
